{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slurm-web.fullname" . }}-agent
  labels:
    app.kubernetes.io/name: {{ include "slurm-web.name" . }}-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  agent.ini: |
    [service]
    cluster = default
    interface = 0.0.0.0
    port = 5012
    debug = false

    [slurmrestd]
    uri = {{ .Values.agent.slurmrestd.uri }}
    auth = jwt
    jwt_mode = auto
    jwt_user = slurm
    jwt_lifespan = 3600
    {{- if .Values.agent.slurmrestd.jwtSecret }}
    jwt_key = /var/lib/slurm-web/slurmrestd/jwt.key
    {{- else }}
    jwt_key = /var/lib/slurm-web/jwt.key
    {{- end }}

    [jwt]
    key = /var/lib/slurm-web/jwt.key
    algorithm = HS256
    audience = slurm-web

    {{- if .Values.redis.enabled }}
    [cache]
    enabled = true
    host = {{ .Values.redis.host | default (printf "%s-redis" (include "slurm-web.fullname" .)) }}
    port = {{ .Values.redis.service.port }}
    {{- else }}
    [cache]
    enabled = false
    {{- end }}

    [policy]
    definition = /usr/share/slurm-web/conf/vendor/policy.yml
    vendor_roles = /usr/share/slurm-web/conf/vendor/policy.ini

    [racksdb]
    enabled = false

    [metrics]
    enabled = false
{{- end }}
