{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slurm-web.fullname" . }}-gateway
  labels:
    app.kubernetes.io/name: {{ include "slurm-web.name" . }}-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  gateway.ini: |
    [service]
    interface = 0.0.0.0
    port = 5011
    debug = false

    [ui]
    host = {{ if .Values.gateway.ingress.enabled }}{{ if .Values.gateway.ingress.tls.enabled }}https{{ else }}http{{ end }}://{{ .Values.gateway.ingress.host }}{{ else }}http://localhost:5011{{ end }}
    enabled = true
    path = /usr/share/slurm-web/frontend

    [agents]
    url = {{ .Values.gateway.agentUrl }}

    [authentication]
    enabled = {{ if eq .Values.gateway.auth.method "none" }}false{{ else }}true{{ end }}
    {{- if ne .Values.gateway.auth.method "none" }}
    method = {{ .Values.gateway.auth.method }}
    {{- end }}

    {{- if eq .Values.gateway.auth.method "ldap" }}
    [ldap]
    uri = {{ .Values.gateway.ldap.uri }}
    user_base = {{ .Values.gateway.ldap.userBase }}
    group_base = {{ .Values.gateway.ldap.groupBase }}
    {{- if .Values.gateway.ldap.bindDn }}
    bind_dn = {{ .Values.gateway.ldap.bindDn }}
    bind_password_file = /etc/slurm-web-secrets/ldap-bind-password
    {{- end }}
    {{- end }}

    [jwt]
    key = /var/lib/slurm-web/jwt.key
    duration = 1
    algorithm = HS256
    audience = slurm-web
{{- end }}
