apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm-web.fullname" . }}-jwt
  labels:
    app.kubernetes.io/name: {{ include "slurm-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  jwt.key: {{ .Values.secrets.jwtKey | b64enc | quote }}
